import{a as m,S as h,i as p}from"./assets/vendor-b11e2a50.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const g="https://pixabay.com/api/",b="44810429-780319b334a9c60538a2ecf11";async function d(t,s=1){const o=`${g}?key=${b}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${s}`,n=await m.get(o);if(n.status!==200)throw new Error("Failed to fetch images");return n.data}let c;function u(t,s=!1){const o=document.querySelector(".gallery"),n=t.map(e=>L(e)).join("");s?o.insertAdjacentHTML("beforeend",n):o.innerHTML=n,c?c.refresh():c=new h(".gallery a"),v()}function L(t){return`
        <div class="photo-card">
            <a href="${t.largeImageURL}">
                <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
            </a>
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${t.likes}</p>
                <p class="info-item"><b>Views:</b> ${t.views}</p>
                <p class="info-item"><b>Comments:</b> ${t.comments}</p>
                <p class="info-item"><b>Downloads:</b> ${t.downloads}</p>
            </div>
        </div>
    `}function i(t){p.error({title:"Error",message:t})}function f(){document.querySelector(".loading").style.display="block"}function l(){document.querySelector(".loading").style.display="none"}function y(){const t=document.querySelector(".gallery");t.innerHTML=""}function v(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}document.addEventListener("DOMContentLoaded",()=>{const t=document.getElementById("search-form"),s=t.querySelector('input[name="query"]'),o=document.querySelector(".load-more");let n="",e=1;t.addEventListener("submit",async r=>{if(r.preventDefault(),n=s.value.trim(),e=1,n===""){i("Please enter a search query"),s.value="";return}try{f();const a=await d(n,e);l(),y(),a.hits.length===0?i("Sorry, there are no images matching your search query. Please try again!"):(u(a.hits),s.value="",a.totalHits>15?o.style.display="block":o.style.display="none")}catch{l(),y(),i("Failed to fetch images. Please try again later."),o.style.display="none"}}),o.addEventListener("click",async()=>{e+=1;try{f();const r=await d(n,e);l(),r.hits.length===0||r.hits.length<15?(o.style.display="none",i("We're sorry, but you've reached the end of search results.")):u(r.hits,!0)}catch{l(),i("Failed to fetch images. Please try again later."),o.style.display="none"}})});
//# sourceMappingURL=commonHelpers.js.map
