import{a as m,S as h,i as p}from"./assets/vendor-b11e2a50.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const g="https://pixabay.com/api/",b="44810429-780319b334a9c60538a2ecf11";async function d(t,n=1){const s=`${g}?key=${b}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${n}`,o=await m.get(s);if(o.status!==200)throw new Error("Failed to fetch images");return o.data}let c;function u(t,n=!1){const s=document.querySelector(".gallery"),o=t.map(e=>L(e)).join("");n?s.insertAdjacentHTML("beforeend",o):s.innerHTML=o,c?c.refresh():c=new h(".gallery a"),v()}function L(t){return`
        <div class="photo-card">
            <a href="${t.largeImageURL}">
                <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
            </a>
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${t.likes}</p>
                <p class="info-item"><b>Views:</b> ${t.views}</p>
                <p class="info-item"><b>Comments:</b> ${t.comments}</p>
                <p class="info-item"><b>Downloads:</b> ${t.downloads}</p>
            </div>
        </div>
    `}function i(t){p.error({title:"Error",message:t})}function f(){document.querySelector(".loading").style.display="block"}function l(){document.querySelector(".loading").style.display="none"}function y(){const t=document.querySelector(".gallery");t.innerHTML=""}function v(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}document.addEventListener("DOMContentLoaded",()=>{const t=document.getElementById("search-form"),n=t.querySelector('input[name="query"]'),s=document.querySelector(".load-more");let o="",e=1;t.addEventListener("submit",async r=>{if(r.preventDefault(),o=n.value.trim(),e=1,o===""){i("Please enter a search query"),n.value="";return}try{f();const a=await d(o,e);l(),y(),a.hits.length===0?i("Sorry, there are no images matching your search query. Please try again!"):(u(a.hits),n.value="",a.totalHits>15?s.style.display="block":s.style.display="none")}catch{l(),y(),i("Failed to fetch images. Please try again later.")}}),s.addEventListener("click",async()=>{e+=1;try{f();const r=await d(o,e);l(),(r.hits.length===0||r.hits.length<15)&&(s.style.display="none",i("We're sorry, but you've reached the end of search results.")),u(r.hits,!0)}catch{l(),i("Failed to fetch images. Please try again later.")}})});
//# sourceMappingURL=commonHelpers.js.map
